### ISSUE TITLE
The generated function FieldMaskWithMode clashes with message field named field_mask_with_mode

### ISSUE THREAD

**Issue by vaidasn** [yeqown/protoc-gen-fieldmask#12]
The generated function `FieldMaskWithMode` clashes with message field named `field_mask_with_mode`. Eg:

```protobuf
message UserInfoRequest {
  string user_id = 1;
  google.protobuf.FieldMask field_mask = 2 [
    (fieldmask.option.Option).in = {gen: true},
    (fieldmask.option.Option).out = {gen: true, message:"UserInfoResponse"}
  ];
  string field_mask_with_mode = 3;
}
```

```
pb/user.pb.fm.go:11:6: type UserInfoRequest has both field and method named FieldMaskWithMode
```

The solution is to rename generate function as `FieldMask_WithMode` following the pattern with other generated functions.

**Comment by yeqown** [comment]
How often do you think this happened? And just rename the field name in your constructed case. I don't think this is so necessary, and though the plugin renamed generate function name, it maybe conflict again.

**Comment by vaidasn** [comment]
This is also a matter of consistency. All other generated functions by the plugin have underscore in the function name.

**Comment by vaidasn** [comment]
Field names with underscore are converted camel case therefore it is not that easy to get field named `FieldMask_WithMode` in go code.

**Comment by yeqown** [comment]
I'm sorry, you can't convince me by such points. I mean other plugins rather than `pb` would cause conflicts. Consistency makes me think about let `FieldMaskWithMode` be an **un-exported** API?

In a word, I don't see the necessity. Why not use it until it becomes a problem?

**Comment by vaidasn** [comment]
Having `fieldMaskWithMode` (i.e. unexported function) could also be a possibility.

**Comment by yeqown** [comment]
Would you like to re-create another PR for this @vaidasn
