### ISSUE TITLE
go install后定义proto的时候如何导入fieldmask.proto，否则无法按按照用法定义

### ISSUE THREAD

**Issue by m430** [yeqown/protoc-gen-fieldmask#15]

**Comment by m430** [comment]
```bash
fieldmask/option.proto:23:31: warning: Extension number 1071 has already been used in "google.protobuf.FieldOptions" by extension "validate.rules" defined in validate/validate.proto.
```

我把目录下的fieldmask相关的proto拷贝我到的项目后发现会跟protobuf的validate里面的`google.protobuf.FieldOptions`定义冲突。这个问题麻烦能看下怎么解决吗

**Comment by yeqown** [comment]
@m430 看起来 extension number 重复了，我了解下这个数是怎么约定；如果你急用的话，你可以先 fork 一份改一个其他的值。

[proto/fieldmask/option.proto](#)

```protobuf
extend google.protobuf.FieldOptions {
  optional FieldMask Option = 1071; // 1071 改成其他数
}
```

然后在根目录执行一下 `make gen-fm-pb`，重新执行安装命令，再运行你的编译命令应该就可以了。

**Comment by yeqown** [comment]
[v0.3.4](https://github.com/yeqown/protoc-gen-fieldmask/releases) 已经替换了 extension number

**Comment by yeqown** [comment]
> [v0.3.4](https://github.com/yeqown/protoc-gen-fieldmask/releases) 已经替换了 extension number

这只是临时的方法；应该是需要申请注册的，我找到了相关的邮件地址，我先试试

**Comment by yeqown** [comment]
Fixed since [v0.3.5](https://github.com/yeqown/protoc-gen-fieldmask/releases/tag/v0.3.5) released.
